/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import accesoADatos.ProductoData;
import entidades.Producto;
import java.sql.Date;
import java.time.LocalDate;
import java.time.ZoneId;
import javax.swing.JOptionPane;

/**
 *
 * @author ApioMan
 */
public class GestorProductos extends javax.swing.JInternalFrame {

    /**
     * Creates new form gestorProductos
     */
    public GestorProductos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfID = new javax.swing.JTextField();
        jBBuscar = new javax.swing.JButton();
        tfNombre = new javax.swing.JTextField();
        nombre = new javax.swing.JLabel();
        descripcion = new javax.swing.JLabel();
        tfDescripcion = new javax.swing.JTextField();
        tfPrecio = new javax.swing.JTextField();
        precio = new javax.swing.JLabel();
        estadoII = new javax.swing.JLabel();
        rbEstado = new javax.swing.JRadioButton();
        nuevo = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        guardar = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tfStock = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        jLabel1.setText("Id:");

        jBBuscar.setBackground(new java.awt.Color(255, 255, 204));
        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        nombre.setText("Nombre:");

        descripcion.setText("Descripción:");

        precio.setText("Precio:");

        estadoII.setText("Estado: ");

        nuevo.setBackground(new java.awt.Color(255, 255, 204));
        nuevo.setText("Nuevo");
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });

        eliminar.setBackground(new java.awt.Color(255, 255, 204));
        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        guardar.setBackground(new java.awt.Color(255, 255, 204));
        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        salir.setBackground(new java.awt.Color(255, 255, 204));
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        jLabel2.setText("Stock");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(salir)))
                .addGap(0, 18, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBBuscar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(estadoII)
                                .addGap(54, 54, 54)
                                .addComponent(rbEstado)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(68, 68, 68)
                                        .addComponent(tfStock, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(nombre)
                                    .addComponent(descripcion)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(precio)
                                        .addGap(61, 61, 61)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(tfDescripcion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                            .addComponent(tfPrecio)))
                                    .addComponent(tfNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBuscar)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(nombre)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(descripcion)
                    .addComponent(tfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(precio)
                    .addComponent(tfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(tfStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(estadoII)
                    .addComponent(rbEstado))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(nuevo)
                    .addComponent(eliminar)
                    .addComponent(guardar)
                    .addComponent(salir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed

        try {
            int id = Integer.parseInt(tfID.getText());
            ProductoData acceso = new ProductoData();
            Producto producto = acceso.buscarProducto(id);
            if (producto != null) {
                tfNombre.setText(producto.getNombreProducto());
                rbEstado.setSelected(producto.isEstado());
                tfDescripcion.setText(producto.getDescripcion());
                tfStock.setText(producto.getStock() + "");
                tfPrecio.setText(producto.getPrecioActual() + "");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error en el campo ID.");
        }

    }//GEN-LAST:event_jBBuscarActionPerformed

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
        vaciar();
    }//GEN-LAST:event_nuevoActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        try {
            int id = Integer.parseInt(tfID.getText());
            ProductoData acceso = new ProductoData();
            acceso.modificarProductoEstado(id);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error en el campo ID.");
        }
        vaciar();
    }//GEN-LAST:event_eliminarActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        ProductoData acceso = new ProductoData();
        Producto producto = null;
        try {
            if (!tfID.getText().equalsIgnoreCase("")) {
                producto = crearProducto();
                boolean existe = acceso.verificarExistencia(producto);

                if (existe) {
                    try {
                        acceso.modificarProducto(producto);
                        vaciar();
                    } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(this, "Error númerico " + e.getMessage());
                    }
                } else {

                    if (descripcion.getText().isEmpty() || nombre.getText().isEmpty()) {
                        JOptionPane.showMessageDialog(this, "No pueden haber campos vacíos.");
                    } else {
                        try {
                            producto = crearProductoSinID();
                            acceso.guardarProducto(producto);
                            vaciar();
                        } catch (NumberFormatException e) {
                            JOptionPane.showMessageDialog(this, "Error númerico " + e.getMessage());
                        }
                    }

                }
            } else {

                if (descripcion.getText().isEmpty() || nombre.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "No pueden haber campos vacíos.");
                } else {
                    try {
                        producto = crearProductoSinID();
                        acceso.guardarProducto(producto);
                        vaciar();
                    } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(this, "Error númerico " + e.getMessage());
                    }
                }

            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error númerico " + e.getMessage());
        }

    }//GEN-LAST:event_guardarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel descripcion;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel estadoII;
    private javax.swing.JButton guardar;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel nombre;
    private javax.swing.JButton nuevo;
    private javax.swing.JLabel precio;
    private javax.swing.JRadioButton rbEstado;
    private javax.swing.JButton salir;
    private javax.swing.JTextField tfDescripcion;
    private javax.swing.JTextField tfID;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfPrecio;
    private javax.swing.JTextField tfStock;
    // End of variables declaration//GEN-END:variables

    private void vaciar() {
        tfID.setText("");
        tfNombre.setText("");
        tfDescripcion.setText("");
        tfPrecio.setText("");
        tfStock.setText("");
        rbEstado.setSelected(false);
    }

    private Producto crearProducto() {
        Producto producto = new Producto();
        producto.setIdProducto(Integer.parseInt(tfID.getText()));
        producto.setNombreProducto(tfNombre.getText());
        producto.setDescripcion(tfDescripcion.getText());
        producto.setPrecioActual(Double.parseDouble(tfPrecio.getText()));
        producto.setStock(Integer.parseInt(tfStock.getText()));
        producto.setEstado(rbEstado.isSelected());
        return producto;
    }

    private Producto crearProductoSinID() {
        Producto producto = new Producto();
        producto.setNombreProducto(tfNombre.getText());
        producto.setDescripcion(tfDescripcion.getText());
        producto.setPrecioActual(Double.parseDouble(tfPrecio.getText()));
        producto.setStock(Integer.parseInt(tfStock.getText()));
        producto.setEstado(rbEstado.isSelected());
        return producto;
    }
}
